
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 25 17:11:48 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 21;
  public static final int CONST = 7;
  public static final int GE = 31;
  public static final int LPAREN = 43;
  public static final int CONTINUE = 17;
  public static final int NUM_CONST = 20;
  public static final int MINUS = 24;
  public static final int RPAREN = 44;
  public static final int SEMICOLON = 39;
  public static final int AND = 34;
  public static final int LT = 32;
  public static final int OR = 35;
  public static final int COMMA = 41;
  public static final int CLASS = 4;
  public static final int INC = 37;
  public static final int DIV = 26;
  public static final int PLUS = 23;
  public static final int IF = 8;
  public static final int DOT = 42;
  public static final int LE = 33;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int LAMBDA = 49;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 25;
  public static final int PERCENT = 27;
  public static final int BREAK = 3;
  public static final int IDENT = 19;
  public static final int VOID = 15;
  public static final int EQ = 36;
  public static final int COLON = 40;
  public static final int FOREACH = 18;
  public static final int LBRACE = 47;
  public static final int ELSE = 6;
  public static final int LSQUARE = 45;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int DEQ = 28;
  public static final int RSQUARE = 46;
  public static final int WHILE = 10;
  public static final int RBRACE = 48;
  public static final int EXTENDS = 16;
  public static final int NE = 29;
  public static final int BOOL_CONST = 22;
  public static final int DEC = 38;
  public static final int GT = 30;
  public static final int PRINT = 12;
  public static final int DO = 9;
}

